### ISSUE TITLE
License

### ISSUE THREAD

**Issue by maawoo** [crisjosil/Sentinel_Earth_Engine#1]
Hi Cristian,
I'm a master's student in Geoinformatics at the University of Jena (Germany). I'm currently working on a project that uses GEE Python API  to get Sentinel-1 backscatter timeseries for locations of ISMN (International Soil Moisture Network) stations. I found this project of yours and some functions contained in EE_library.py helped me a lot! 
Because you didn't specify a license, I wanted to ask if it's okay if I use some of those functions in my project? I will cite you as the author in the docstrings of course!

Thanks and regards,
Marco

**Comment by crisjosil** [comment]
Hi Marco,

Thanks for getting in touch. I'm glad it helped you and off course feel free to use it. I've learnt through a lot of online resources so I have also benefited from open source code.

Hope your project ends very well.

Thanks.

Cristian S.
PhD student.


________________________________

**Comment by maawoo** [comment]
Great, thank you! :)
